---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi9/ubi
    tmpfs:
      - /run
      - /tmp
    privileged: true
    command: /usr/sbin/init
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible